[build]
target = "xtensa-esp32s3-none-elf"

[target.'cfg(target_arch = "xtensa")']
runner    = "espflash flash --monitor --partition-table=partitions.csv"
rustflags = [
  # GNU LD
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",

  # LLD
  # "-C", "link-arg=-Tlinkall.x",
  # "-C", "linker=rust-lld",
]


[env]
ESP_LOG = "error"

[unstable]
build-std = ["alloc", "core"]