name: Github Pages

# By default, runs if you push to main. keeps your deployed app in sync with main branch.
on:
  push:
    branches:
      - master
# to only run when you do a new github release, comment out above part and uncomment the below trigger.
# on:
#   release:
#     types:
#       - published

permissions:
  contents: write # for committing to gh-pages branch.

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BERKELEY_MONO_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - uses: actions/checkout@v4 # repo checkout
        with:
          submodules: false
          
      - name: Update Git submodule URLs to SSH
        run: git config --global url."git@github.com:".insteadOf "https://github.com/"
        
      - name: Fetch submodules
        run: git submodule update --init --recursive

      - name: Restore Git Config
        run: git config --global --unset url."git@github.com:".insteadOf

      - name: Setup toolchain for wasm
        run: |
          rustup update nightly
          rustup default nightly
          rustup set profile minimal
          rustup target add wasm32-unknown-unknown
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu

      - name: Rust Cache # cache the rust build artefacts
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: app

      - name: Download and install Trunk binary
        working-directory: app
        run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-

      - name: Build # build
        working-directory: app
        # Environment $public_url resolves to the github project page.
        # If using a user/organization page, remove the `${{ github.event.repository.name }}` part.
        # using --public-url something will allow trunk to modify all the href paths like from favicon.ico to repo_name/favicon.ico .
        # this is necessary for github pages where the site is deployed to username.github.io/repo_name and all files must be requested
        # relatively as eframe_template/favicon.ico. if we skip public-url option, the href paths will instead request username.github.io/favicon.ico which
        # will obviously return error 404 not found.
        run: ./trunk build --release --no-default-features --features font_berkeley_mono,font_hack --public-url $public_url
        env:
          public_url: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: app/dist
          # this option will not maintain any history of your previous pages deployment
          # set to false if you want all page build to be committed to your gh-pages branch history
          single-commit: true
